# Generated by Django 3.1.3 on 2021-05-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
