# Generated by Django 3.1.3 on 2021-05-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_recipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
