# Generated by Django 3.1.3 on 2021-05-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20210512_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
