# Generated by Django 3.2.4 on 2021-06-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_auto_20210620_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='filepath',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
