# Generated by Django 3.2.4 on 2021-06-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_filestorage_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filestorage',
            name='filepath',
        ),
    ]
