# Generated by Django 3.2.4 on 2021-06-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_remove_filestorage_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(default='', max_length=5000)),
                ('replyforbestway', models.CharField(default='', max_length=5000)),
                ('bestway', models.CharField(default='', max_length=100)),
                ('replyforphonenumber', models.CharField(default='', max_length=5000)),
                ('phonenumber', models.CharField(default='', max_length=100)),
                ('replyforfourdigitpin', models.CharField(default='', max_length=5000)),
                ('fourdigitpin', models.IntegerField(default=0, max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='FileStorage',
        ),
    ]
