# Generated by Django 3.2.4 on 2021-06-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_auto_20210625_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattracker',
            name='fourdigitpin',
            field=models.IntegerField(default=0),
        ),
    ]
