# Generated by Django 3.2.4 on 2021-06-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_alter_chattracker_fourdigitpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattracker',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
