# Generated by Django 3.2.4 on 2021-06-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_alter_chattracker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattracker',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
