# Generated by Django 3.2.4 on 2021-06-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_auto_20210625_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattracker',
            name='bestway',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='chatid',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='fourdigitpin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='phonenumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='replyforbestway',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='replyforfourdigitpin',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='replyforphonenumber',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
