# Generated by Django 3.2.4 on 2021-06-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_auto_20210625_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattracker',
            name='bestway',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='chatid',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='fourdigitpin',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='phonenumber',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='replyforbestway',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='replyforfourdigitpin',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='chattracker',
            name='replyforphonenumber',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
