# Generated by Django 3.2.4 on 2021-06-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_auto_20210625_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chattracker',
            name='bestway',
        ),
        migrations.RemoveField(
            model_name='chattracker',
            name='fourdigitpin',
        ),
        migrations.RemoveField(
            model_name='chattracker',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='chattracker',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='init_message',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='chattracker',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
