# Generated by Django 3.2.4 on 2021-06-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_auto_20210625_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTracker1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(blank=True, default='', max_length=5000)),
                ('fivedigitpin', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
