# Generated by Django 3.2.4 on 2021-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_auto_20210629_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(blank=True, default='', max_length=100)),
                ('SerialNumber', models.CharField(blank=True, default='', max_length=100)),
                ('Platform', models.CharField(blank=True, default='', max_length=100)),
                ('AppVersion', models.CharField(blank=True, default='', max_length=100)),
                ('State', models.CharField(blank=True, default='', max_length=100)),
                ('SaleTypeId', models.IntegerField(blank=True, default=0)),
                ('Latitude', models.FloatField(blank=True, default=0)),
                ('Longitude', models.FloatField(blank=True, default=0)),
                ('Result', models.BooleanField(blank=True, default='')),
                ('OrderNumber', models.IntegerField(blank=True, default=0)),
                ('OrderDate', models.DateTimeField(blank=True, default='')),
                ('PackageID', models.CharField(blank=True, default='', max_length=100)),
                ('Status', models.CharField(blank=True, default='', max_length=100)),
                ('Message', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.CharField(blank=True, default='', max_length=100)),
                ('FirstName', models.CharField(blank=True, default='', max_length=100)),
                ('LastName', models.CharField(blank=True, default='', max_length=100)),
                ('ZipFilePassword', models.CharField(blank=True, default='', max_length=100)),
                ('RequirePhoneNumber', models.BooleanField(blank=True, default='')),
                ('RequireEmailAddress', models.BooleanField(blank=True, default='')),
                ('ReservationApiVersion', models.CharField(blank=True, default='', max_length=100)),
                ('ReservationUserCode', models.CharField(blank=True, default='', max_length=100)),
                ('ReservationAgentCode', models.CharField(blank=True, default='', max_length=100)),
                ('ReservationClientCode', models.CharField(blank=True, default='', max_length=100)),
                ('ReservationVenderCode', models.CharField(blank=True, default='', max_length=100)),
                ('ECommCaliforniaFlow', models.CharField(blank=True, default='', max_length=100)),
                ('Status', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
