# Generated by Django 3.2.4 on 2021-06-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_chattracker1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattracker1',
            old_name='fivedigitpin',
            new_name='fivedigits',
        ),
    ]
