# Generated by Django 3.2.4 on 2021-06-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_rename_fivedigitpin_chattracker1_fivedigits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatTracker1',
            new_name='FlowChatTracker',
        ),
    ]
