# Generated by Django 3.2.4 on 2021-06-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_rename_chattracker1_flowchattracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowChatEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(blank=True, default='', max_length=5000)),
                ('emailAddress', models.EmailField(max_length=50)),
            ],
        ),
    ]
