# Generated by Django 3.2.4 on 2021-06-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0023_flowchatemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowchatemail',
            name='bestway',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flowchattracker',
            name='bestway',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
