# Generated by Django 3.2.4 on 2021-06-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0024_auto_20210629_1738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlowChatEmail',
        ),
        migrations.AddField(
            model_name='flowchattracker',
            name='emailAddress',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
