# Generated by Django 3.2.4 on 2021-06-29 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0025_auto_20210629_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowchattracker',
            old_name='fivedigits',
            new_name='zipCode',
        ),
    ]
