# Generated by Django 3.2.4 on 2021-06-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0026_rename_fivedigits_flowchattracker_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatTracker',
        ),
    ]
